Fixed WalletConnectQRImage class multiple handler bug on enable/disable.
WalletConnect/WalletConnectUnity pull request #25
Opened 2021-12-03 04:57 UTC by AlLansley

- Modified QR code image size to be smaller & hence consume less texture memory,
- Made QR code texture use point / nearest filtering to preserve sharp edges of pixel blocks,
- Added comments.

2021-12-06 03:30 UTC, gigajuwels commented
@ecp4224 please review

2021-12-06 04:23 UTC, ecp4224 requested changes
Everything LGTM, just one small change to use new events

2021-12-06 04:23 UTC, ecp4224 commented on Assets/WalletConnectUnity/Scripts/WalletConnectSharp.Unity/UI/WalletConnectQRImage.cs
> +            walletConnect.ConnectionStarted += WalletConnectOnConnectionStarted;
I guess we should be using the new `walletConnect.NewSessionStarted` event handler to only trigger a QRCode update when a new session is created. 

Having the bool flag check here is still needed so we dont subscribe more than once

2021-12-08 05:14 UTC, ecp4224 commented on Assets/WalletConnectUnity/Scripts/WalletConnectSharp.Unity/UI/WalletConnectQRImage.cs
> +            walletConnect.ConnectionStarted += WalletConnectOnConnectionStarted;
Actually never mind, we want the QR Code to generate when we connect to the bridge, not after the session gets created/connected

2021-12-08 05:14 UTC, ecp4224 approved these changes

2021-12-08 05:14 UTC, merged